version: '2'

services:
    srcbackend:
        volumes:
            - .:/src

            # necessary to prevent OS X node_modules being loaded in:
            - /src/backend/node_modules

        build:
            context: ./backend
            dockerfile: ./Dockerfile

        ports:
          - "8080:8080"
